// Extracts the Galmuri9 bitmap glyphs needed by the Korean strings into src/galmuri9-glyphs.ts.
//
// Galmuri9's TrueType outlines are not aligned to the pixel grid, so browsers anti-alias them;
// the author's BDF bitmaps are the exact pixel design. This script reads the BDF shipped in the
// `galmuri` npm package and keeps only the characters that appear in src/i18n.ts (plus the ASCII
// range the 5x7 bitmap font lacks), so the game stays crisp and offline-safe while the full web
// font (linked from index.html) remains a fallback for anything else.
//
// Usage: npm run gen:glyphs   (re-run after editing the Korean strings; a test checks coverage)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const bdfPath = path.join(root, 'node_modules', 'galmuri', 'dist', 'Galmuri9.bdf');
const i18nPath = path.join(root, 'src', 'i18n.ts');
const outPath = path.join(root, 'src', 'galmuri9-glyphs.ts');

const bdf = fs.readFileSync(bdfPath, 'utf8');
const version = JSON.parse(fs.readFileSync(path.join(root, 'node_modules', 'galmuri', 'package.json'), 'utf8')).version;

// Every non-ASCII character in the i18n source (the Korean table, arrows, dashes...).
const wanted = new Set();
for (const ch of fs.readFileSync(i18nPath, 'utf8')) {
  if (ch.codePointAt(0) > 0x7e) wanted.add(ch);
}

const ascentMatch = /^FONT_ASCENT (\d+)/m.exec(bdf);
const ascent = ascentMatch ? Number(ascentMatch[1]) : 11;

const glyphs = new Map();
for (const block of bdf.split('STARTCHAR').slice(1)) {
  const enc = /ENCODING (-?\d+)/.exec(block);
  if (!enc) continue;
  const code = Number(enc[1]);
  if (code < 0) continue;
  const ch = String.fromCodePoint(code);
  if (!wanted.has(ch)) continue;
  const dw = /DWIDTH (-?\d+)/.exec(block);
  const bbx = /BBX (-?\d+) (-?\d+) (-?\d+) (-?\d+)/.exec(block);
  const bitmap = /BITMAP\s*\n([\s\S]*?)ENDCHAR/.exec(block);
  if (!dw || !bbx || !bitmap) continue;
  const rows = bitmap[1].trim().split(/\s+/).filter(Boolean);
  glyphs.set(ch, [Number(dw[1]), Number(bbx[3]), Number(bbx[4]), Number(bbx[1]), Number(bbx[2]), rows.join(' ')]);
}

const missing = [...wanted].filter((ch) => !glyphs.has(ch));
const entries = [...glyphs.entries()].sort(([a], [b]) => a.codePointAt(0) - b.codePointAt(0));
const lines = entries.map(([ch, g]) => `  ${JSON.stringify(ch)}: [${g[0]}, ${g[1]}, ${g[2]}, ${g[3]}, ${g[4]}, '${g[5]}'],`);
const src = `// GENERATED by scripts/gen-galmuri.mjs from Galmuri9 ${version} (c) Lee Minseo (quiple), SIL OFL 1.1 (see public/THIRD_PARTY_NOTICES.md).
// Do not edit by hand: change the strings in src/i18n.ts and run \`npm run gen:glyphs\`.
//
// Each glyph: [advance, xOffset, yOffset, width, height, hex rows]. Offsets are BDF-style (from the
// origin on the baseline, y up); each hex row holds the glyph's pixels MSB first.

export type GalmuriGlyph = readonly [number, number, number, number, number, string];

/** Pixels from the baseline to the top of the font's ascent. */
export const GALMURI_ASCENT = ${ascent};

export const GALMURI_GLYPHS: Readonly<Record<string, GalmuriGlyph>> = {
${lines.join('\n')}
};
`;
fs.writeFileSync(outPath, src);
console.log(`wrote ${entries.length} glyphs to ${path.relative(root, outPath)}${missing.length ? `; not in Galmuri9: ${missing.join(' ')}` : ''}`);
